### ISSUE TITLE
why 2 issues repositories ?

### ISSUE THREAD

**Issue by Macadoshis** [DbMaintain/dbmaintain#23]
Why are there still unresolved issues here https://unitils.atlassian.net/projects/DBM/issues/ and only 5 issues ever declared on github ?
Are there 2 different life cycles ?

**Comment by finsterwalder** [comment]
We moved the dbmaintain project to Github, when we started to work on it more.
The Atlassian-Jira is no longer maintained. We never moved the tickets from there and just ignored them.
If you still have problems with one of the issues listed there, please create a new ticket on Github.

**Comment by Macadoshis** [comment]
And as the old saying goes : "_A bug ignored is a bug fixed_"
Way to go fellas :beers: :clap: :100: :+1:

**Comment by stokito** [comment]
Hi @finsterwalder I see that you are one of [original developers](https://sourceforge.net/p/dbmaintain/_members/) of DBMaintain.
Can you explain why do you created a fork instead of maintaining original DBMaintain?
I see that DBMaintain site was last updated in 2011 but in Maven Central there is some more recent artifacts.
We would like to use DBMaintain in our quite big enterprise project  but we can't trust to any forks and we'll prefer to use original technology instead or use any competitor like Liquebase or Flyway because we'll be sure that it will be supported in feature

**Comment by finsterwalder** [comment]
Hi Sergey,

thanks for reaching out.
Actually DBMaintain is now maintained by us on GitHub. The project was more
or less abandoned and we picked it up.
So this is the "original" version of DBMaintain, at least the one that is
still maintained by us.
This is in accordance with the old Maintainers.
The old version was maintained by Tim Ducheyne. Only he has access to the
official Website.
It's a little hard to get a hold of him, so the site is no longer
maintained.
I know we should shut down the old site to avoid confusion, but we are not
able to do that at this moment.

Greetings,
   Malte

**Comment by remast** [comment]
@stokito we are also using DbMaintain as standard tool in a big insurance company and are therefore interested in keeping the project alive.
